// ─────────────────────────────────────────────────────────────────────────────
// CITY DATABASE — 392 cities worldwide
// col = estimated annual living expenses in USD
// state = key into STATE_TAX for local tax rate
// ─────────────────────────────────────────────────────────────────────────────

/** Last reviewed promotion date for the US city cost baselines below. */
export const US_CITY_COST_DATA_UPDATED = 'September 17, 2026'

export interface City {
  name: string;
  key: string;
  col: number;      // annual USD expenses — the one number everything calculates from
  state: string;    // tax key
  flag: string;
  /**
   * A plausible range around `col`, for display only.
   *
   * A single figure has to be right; a range only has to contain the truth,
   * which is a burden this data can actually carry — and showing one tells the
   * reader plainly that it is an estimate. The ends are measurements rather
   * than error bars: what sitting tenants pay against what recent arrivals
   * pay, widened by the Census margin of error. See docs/cost-of-living.md.
   *
   * Deliberately NOT used in any calculation. A FIRE target cannot be
   * multiplied out of an interval, so `col` stays the single input and these
   * only ever reach the page.
   */
  colLow?: number;
  colHigh?: number;
}

export interface CityCostRange {
  /** The figure to lead with, and the only one anything is calculated from. */
  mid: number;
  low: number;
  high: number;
  /**
   * True where the top of the range is a ceiling rather than a measurement.
   *
   * Census top-codes median rent at $3,501, so in the priciest cities the
   * upper bound stops where the survey stops, not where the rents do. Left
   * unmarked, such a city reads as a $200 band — a claim of precision in
   * exactly the places the data is blindest. Render these as a floor.
   */
  capped: boolean;
}

/**
 * The range to show for a city, or null where there is nothing measured.
 *
 * Null rather than a made-up band: a city whose range we have not imported
 * gets a plain number, which is honest. Inventing a spread around it would
 * dress a guess up as a measurement, which is the whole failure this range
 * exists to avoid.
 */
export function costRangeFor(city: Pick<City, "col" | "colLow" | "colHigh">): CityCostRange | null {
  const { col, colLow, colHigh } = city;
  if (colLow == null || colHigh == null) return null;
  if (!(colLow <= col && col <= colHigh)) return null;
  if (colHigh <= colLow) return null;
  // The importer widens the top bound past `col` for every city it can measure.
  // Where it did not, the cap truncated it.
  return { mid: col, low: colLow, high: colHigh, capped: colHigh === col };
}

export const CITIES: City[] = [
  // ── UNITED STATES ── California
  { name: 'San Francisco, CA',    key: 'sf', col: 72700, colLow: 65100, colHigh: 73900, state: 'ca', flag: '🇺🇸' },
  { name: 'Los Angeles, CA',      key: 'la', col: 64200, colLow: 58700, colHigh: 64600, state: 'ca', flag: '🇺🇸' },
  { name: 'San Diego, CA',        key: 'sandiego', col: 69300, colLow: 62200, colHigh: 70100, state: 'ca', flag: '🇺🇸' },
  { name: 'San Jose, CA',         key: 'sanjose', col: 69400, colLow: 65800, colHigh: 70600, state: 'ca', flag: '🇺🇸' },
  { name: 'Sacramento, CA',       key: 'sacramento', col: 59300, colLow: 55300, colHigh: 60200, state: 'ca', flag: '🇺🇸' },
  { name: 'Oakland, CA',          key: 'oakland', col: 64900, colLow: 59200, colHigh: 65900, state: 'ca', flag: '🇺🇸' },
  { name: 'Fresno, CA',           key: 'fresno', col: 55100, colLow: 51200, colHigh: 55900, state: 'ca', flag: '🇺🇸' },
  { name: 'Long Beach, CA',       key: 'longbeach', col: 61700, colLow: 57400, colHigh: 62600, state: 'ca', flag: '🇺🇸' },
  // New York
  { name: 'New York City, NY',    key: 'nyc', col: 77500, colLow: 61800, colHigh: 78800, state: 'nyc', flag: '🇺🇸' },
  { name: 'Brooklyn, NY',         key: 'brooklyn', col: 67400, colLow: 56900, colHigh: 68400, state: 'nyc', flag: '🇺🇸' },
  { name: 'Buffalo, NY',          key: 'buffalo', col: 48800, colLow: 45400, colHigh: 49500, state: 'ny', flag: '🇺🇸' },
  { name: 'Albany, NY',           key: 'albany', col: 51600, colLow: 46600, colHigh: 53200, state: 'ny', flag: '🇺🇸' },
  // Texas
  { name: 'Austin, TX',           key: 'austin', col: 54300, colLow: 52700, colHigh: 54700, state: 'tx', flag: '🇺🇸' },
  { name: 'Dallas, TX',           key: 'dallas', col: 54500, colLow: 51700, colHigh: 54900, state: 'tx', flag: '🇺🇸' },
  { name: 'Houston, TX',          key: 'houston', col: 50800, colLow: 49400, colHigh: 51100, state: 'tx', flag: '🇺🇸' },
  { name: 'San Antonio, TX',      key: 'sanantonio', col: 49000, colLow: 47900, colHigh: 49300, state: 'tx', flag: '🇺🇸' },
  { name: 'Fort Worth, TX',       key: 'fortworth', col: 54600, colLow: 52000, colHigh: 55200, state: 'tx', flag: '🇺🇸' },
  { name: 'El Paso, TX',          key: 'elpaso', col: 46500, colLow: 44600, colHigh: 47100, state: 'tx', flag: '🇺🇸' },
  { name: 'Plano, TX',            key: 'plano', col: 56100, colLow: 54600, colHigh: 56800, state: 'tx', flag: '🇺🇸' },
  // Florida
  { name: 'Miami, FL',            key: 'miami', col: 65100, colLow: 56100, colHigh: 66400, state: 'fl', flag: '🇺🇸' },
  { name: 'Orlando, FL',          key: 'orlando', col: 55500, colLow: 53700, colHigh: 56000, state: 'fl', flag: '🇺🇸' },
  { name: 'Tampa, FL',            key: 'tampa', col: 58100, colLow: 52400, colHigh: 58900, state: 'fl', flag: '🇺🇸' },
  { name: 'Jacksonville, FL',     key: 'jacksonville', col: 52800, colLow: 50300, colHigh: 53300, state: 'fl', flag: '🇺🇸' },
  { name: 'Fort Lauderdale, FL',  key: 'fortlauderdale', col: 60200, colLow: 56200, colHigh: 62500, state: 'fl', flag: '🇺🇸' },
  { name: 'St. Petersburg, FL',   key: 'stpete', col: 56100, colLow: 51800, colHigh: 57100, state: 'fl', flag: '🇺🇸' },
  { name: 'Sarasota, FL',         key: 'sarasota', col: 55300, colLow: 49300, colHigh: 59400, state: 'fl', flag: '🇺🇸' },
  // Pacific Northwest
  { name: 'Seattle, WA',          key: 'seattle', col: 61600, colLow: 59600, colHigh: 62300, state: 'wa', flag: '🇺🇸' },
  { name: 'Portland, OR',         key: 'portland', col: 56100, colLow: 54300, colHigh: 56500, state: 'or', flag: '🇺🇸' },
  { name: 'Spokane, WA',          key: 'spokane', col: 51500, colLow: 48400, colHigh: 52500, state: 'wa', flag: '🇺🇸' },
  { name: 'Tacoma, WA',           key: 'tacoma', col: 57900, colLow: 55300, colHigh: 58600, state: 'wa', flag: '🇺🇸' },
  { name: 'Eugene, OR',           key: 'eugene', col: 53100, colLow: 50500, colHigh: 54300, state: 'or', flag: '🇺🇸' },
  // Mountain West
  { name: 'Denver, CO',           key: 'denver', col: 57500, colLow: 55500, colHigh: 58000, state: 'co', flag: '🇺🇸' },
  { name: 'Boulder, CO',          key: 'boulder', col: 58400, colLow: 56200, colHigh: 59700, state: 'co', flag: '🇺🇸' },
  { name: 'Colorado Springs, CO', key: 'cosprings', col: 54800, colLow: 52400, colHigh: 55500, state: 'co', flag: '🇺🇸' },
  { name: 'Salt Lake City, UT',   key: 'slc', col: 51400, colLow: 48900, colHigh: 52700, state: 'ut', flag: '🇺🇸' },
  { name: 'Provo, UT',            key: 'provo', col: 48800, colLow: 46100, colHigh: 50200, state: 'ut', flag: '🇺🇸' },
  { name: 'Boise, ID',            key: 'boise', col: 52600, colLow: 50000, colHigh: 53100, state: 'id', flag: '🇺🇸' },
  { name: 'Phoenix, AZ',          key: 'phoenix', col: 55300, colLow: 52500, colHigh: 55700, state: 'az', flag: '🇺🇸' },
  { name: 'Tucson, AZ',           key: 'tucson', col: 48800, colLow: 46500, colHigh: 49500, state: 'az', flag: '🇺🇸' },
  { name: 'Scottsdale, AZ',       key: 'scottsdale', col: 59600, colLow: 56800, colHigh: 60600, state: 'az', flag: '🇺🇸' },
  { name: 'Las Vegas, NV',        key: 'lasvegas', col: 53600, colLow: 51400, colHigh: 54200, state: 'nv', flag: '🇺🇸' },
  { name: 'Reno, NV',             key: 'reno', col: 53400, colLow: 51100, colHigh: 54100, state: 'nv', flag: '🇺🇸' },
  { name: 'Albuquerque, NM',      key: 'albuquerque', col: 49000, colLow: 46000, colHigh: 49800, state: 'nm', flag: '🇺🇸' },
  { name: 'Santa Fe, NM',         key: 'santafe', col: 54700, colLow: 49200, colHigh: 56200, state: 'nm', flag: '🇺🇸' },
  // Southeast
  { name: 'Atlanta, GA',          key: 'atlanta', col: 56300, colLow: 53400, colHigh: 56900, state: 'ga', flag: '🇺🇸' },
  { name: 'Savannah, GA',         key: 'savannah', col: 52800, colLow: 48900, colHigh: 53600, state: 'ga', flag: '🇺🇸' },
  { name: 'Charlotte, NC',        key: 'charlotte', col: 54600, colLow: 52000, colHigh: 55000, state: 'nc', flag: '🇺🇸' },
  { name: 'Raleigh, NC',          key: 'raleigh', col: 53900, colLow: 51500, colHigh: 54300, state: 'nc', flag: '🇺🇸' },
  { name: 'Asheville, NC',        key: 'asheville', col: 55300, colLow: 48300, colHigh: 56900, state: 'nc', flag: '🇺🇸' },
  { name: 'Nashville, TN',        key: 'nashville', col: 54000, colLow: 51100, colHigh: 54400, state: 'tn', flag: '🇺🇸' },
  { name: 'Memphis, TN',          key: 'memphis', col: 48600, colLow: 46100, colHigh: 49200, state: 'tn', flag: '🇺🇸' },
  { name: 'Chattanooga, TN',      key: 'chattanooga', col: 50000, colLow: 47000, colHigh: 50600, state: 'tn', flag: '🇺🇸' },
  { name: 'New Orleans, LA',      key: 'neworleans', col: 49400, colLow: 46300, colHigh: 50300, state: 'la', flag: '🇺🇸' },
  { name: 'Baton Rouge, LA',      key: 'batonrouge', col: 44800, colLow: 44200, colHigh: 45600, state: 'la', flag: '🇺🇸' },
  { name: 'Richmond, VA',         key: 'richmond', col: 51900, colLow: 48900, colHigh: 52700, state: 'va', flag: '🇺🇸' },
  { name: 'Virginia Beach, VA',   key: 'vabeach', col: 55100, colLow: 53200, colHigh: 55700, state: 'va', flag: '🇺🇸' },
  { name: 'Charleston, SC',       key: 'charleston', col: 57200, colLow: 52500, colHigh: 58500, state: 'sc', flag: '🇺🇸' },
  { name: 'Columbia, SC',         key: 'columbia_sc', col: 49000, colLow: 46200, colHigh: 50300, state: 'sc', flag: '🇺🇸' },
  { name: 'Birmingham, AL',       key: 'birmingham', col: 47500, colLow: 45200, colHigh: 48400, state: 'al', flag: '🇺🇸' },
  { name: 'Huntsville, AL',       key: 'huntsville', col: 48400, colLow: 45900, colHigh: 49300, state: 'al', flag: '🇺🇸' },
  { name: 'Jackson, MS',          key: 'jackson_ms', col: 47300, colLow: 43600, colHigh: 49100, state: 'ms', flag: '🇺🇸' },
  { name: 'Little Rock, AR',      key: 'littlerock', col: 46700, colLow: 44500, colHigh: 47500, state: 'ar_us', flag: '🇺🇸' },
  // Midwest
  { name: 'Chicago, IL',          key: 'chicago', col: 56800, colLow: 52000, colHigh: 57400, state: 'il', flag: '🇺🇸' },
  { name: 'Minneapolis, MN',      key: 'minneapolis', col: 53200, colLow: 51000, colHigh: 53900, state: 'mn', flag: '🇺🇸' },
  { name: 'Columbus, OH',         key: 'columbus', col: 50300, colLow: 48000, colHigh: 50700, state: 'oh', flag: '🇺🇸' },
  { name: 'Cleveland, OH',        key: 'cleveland', col: 46700, colLow: 43600, colHigh: 47200, state: 'oh', flag: '🇺🇸' },
  { name: 'Cincinnati, OH',       key: 'cincinnati', col: 47800, colLow: 44000, colHigh: 48600, state: 'oh', flag: '🇺🇸' },
  { name: 'Kansas City, MO',      key: 'kansascity', col: 48600, colLow: 46200, colHigh: 49100, state: 'mo', flag: '🇺🇸' },
  { name: 'St. Louis, MO',        key: 'stlouis', col: 47900, colLow: 45000, colHigh: 48700, state: 'mo', flag: '🇺🇸' },
  { name: 'Detroit, MI',          key: 'detroit', col: 48900, colLow: 46500, colHigh: 49600, state: 'mi', flag: '🇺🇸' },
  { name: 'Grand Rapids, MI',     key: 'grandrapids', col: 51900, colLow: 46800, colHigh: 53200, state: 'mi', flag: '🇺🇸' },
  { name: 'Indianapolis, IN',     key: 'indianapolis', col: 48800, colLow: 46300, colHigh: 49300, state: 'in_us', flag: '🇺🇸' },
  { name: 'Milwaukee, WI',        key: 'milwaukee', col: 46800, colLow: 45100, colHigh: 47300, state: 'wi', flag: '🇺🇸' },
  { name: 'Madison, WI',          key: 'madison', col: 51600, colLow: 49100, colHigh: 52400, state: 'wi', flag: '🇺🇸' },
  { name: 'Omaha, NE',            key: 'omaha', col: 47500, colLow: 45500, colHigh: 48000, state: 'ne', flag: '🇺🇸' },
  { name: 'Des Moines, IA',       key: 'desmoines', col: 45400, colLow: 44100, colHigh: 46100, state: 'ia', flag: '🇺🇸' },
  { name: 'Sioux Falls, SD',      key: 'siouxfalls', col: 46100, colLow: 43400, colHigh: 46900, state: 'sd', flag: '🇺🇸' },
  { name: 'Fargo, ND',            key: 'fargo', col: 43500, colLow: 42500, colHigh: 44200, state: 'nd', flag: '🇺🇸' },
  { name: 'Oklahoma City, OK',    key: 'okc', col: 47300, colLow: 45100, colHigh: 48000, state: 'ok', flag: '🇺🇸' },
  { name: 'Tulsa, OK',            key: 'tulsa', col: 45900, colLow: 44500, colHigh: 46200, state: 'ok', flag: '🇺🇸' },
  { name: 'Wichita, KS',          key: 'wichita', col: 44500, colLow: 43000, colHigh: 45100, state: 'ks', flag: '🇺🇸' },
  // Northeast
  { name: 'Boston, MA',           key: 'boston', col: 68400, colLow: 59200, colHigh: 69600, state: 'ma', flag: '🇺🇸' },
  { name: 'Cambridge, MA',        key: 'cambridge', col: 71400, colLow: 66100, colHigh: 73300, state: 'ma', flag: '🇺🇸' },
  { name: 'Providence, RI',       key: 'providence', col: 55300, colLow: 49600, colHigh: 56400, state: 'ri', flag: '🇺🇸' },
  { name: 'Hartford, CT',         key: 'hartford', col: 50700, colLow: 48100, colHigh: 51800, state: 'ct', flag: '🇺🇸' },
  { name: 'New Haven, CT',        key: 'newhaven', col: 55900, colLow: 50500, colHigh: 57200, state: 'ct', flag: '🇺🇸' },
  { name: 'Philadelphia, PA',     key: 'philadelphia', col: 53700, colLow: 50300, colHigh: 54200, state: 'pa', flag: '🇺🇸' },
  { name: 'Pittsburgh, PA',       key: 'pittsburgh', col: 51300, colLow: 47900, colHigh: 52300, state: 'pa', flag: '🇺🇸' },
  { name: 'Washington DC',        key: 'dc', col: 62200, colLow: 58000, colHigh: 62900, state: 'dc', flag: '🇺🇸' },
  { name: 'Baltimore, MD',        key: 'baltimore', col: 53100, colLow: 49600, colHigh: 54100, state: 'md', flag: '🇺🇸' },
  { name: 'Bethesda, MD',         key: 'bethesda', col: 66700, colLow: 60500, colHigh: 70500, state: 'md', flag: '🇺🇸' },
  { name: 'Newark, NJ',           key: 'newark', col: 57000, colLow: 52400, colHigh: 58000, state: 'nj', flag: '🇺🇸' },
  { name: 'Jersey City, NJ',      key: 'jerseycity', col: 68700, colLow: 59600, colHigh: 70000, state: 'nj', flag: '🇺🇸' },
  { name: 'Hoboken, NJ',          key: 'hoboken', col: 77800, colLow: 71100, colHigh: 77800, state: 'nj', flag: '🇺🇸' },
  { name: 'Burlington, VT',       key: 'burlington', col: 54800, colLow: 50600, colHigh: 57800, state: 'vt', flag: '🇺🇸' },
  { name: 'Portland, ME',         key: 'portland_me', col: 58800, colLow: 50700, colHigh: 61100, state: 'me', flag: '🇺🇸' },
  { name: 'Concord, NH',          key: 'concord_nh', col: 59600, colLow: 47400, colHigh: 64000, state: 'nh', flag: '🇺🇸' },
  // Additional US coverage — more major metros, college towns, suburbs, and state capitals
  { name: 'Anaheim, CA',          key: 'anaheim', col: 64900, colLow: 60800, colHigh: 66200, state: 'ca', flag: '🇺🇸' },
  { name: 'Irvine, CA',           key: 'irvine', col: 74000, colLow: 69800, colHigh: 75700, state: 'ca', flag: '🇺🇸' },
  { name: 'Santa Ana, CA',        key: 'santaana', col: 65500, colLow: 58300, colHigh: 67800, state: 'ca', flag: '🇺🇸' },
  { name: 'Riverside, CA',        key: 'riverside', col: 61900, colLow: 56300, colHigh: 63000, state: 'ca', flag: '🇺🇸' },
  { name: 'Bakersfield, CA',      key: 'bakersfield', col: 57700, colLow: 51100, colHigh: 59200, state: 'ca', flag: '🇺🇸' },
  { name: 'Stockton, CA',         key: 'stockton', col: 56900, colLow: 52400, colHigh: 58300, state: 'ca', flag: '🇺🇸' },
  { name: 'Modesto, CA',          key: 'modesto', col: 57400, colLow: 53800, colHigh: 58700, state: 'ca', flag: '🇺🇸' },
  { name: 'Santa Rosa, CA',       key: 'santarosa', col: 62000, colLow: 58800, colHigh: 63900, state: 'ca', flag: '🇺🇸' },
  { name: 'Santa Barbara, CA',    key: 'santabarbara', col: 67200, colLow: 60500, colHigh: 70500, state: 'ca', flag: '🇺🇸' },
  { name: 'Ventura, CA',          key: 'ventura', col: 62500, colLow: 59300, colHigh: 64500, state: 'ca', flag: '🇺🇸' },
  { name: 'Monterey, CA',         key: 'monterey', col: 68000, colLow: 61000, colHigh: 70800, state: 'ca', flag: '🇺🇸' },
  { name: 'Rochester, NY',        key: 'rochester_ny', col: 48100, colLow: 45800, colHigh: 48800, state: 'ny', flag: '🇺🇸' },
  { name: 'Syracuse, NY',         key: 'syracuse', col: 48000, colLow: 45300, colHigh: 48800, state: 'ny', flag: '🇺🇸' },
  { name: 'Yonkers, NY',          key: 'yonkers', col: 62400, colLow: 55400, colHigh: 64300, state: 'ny', flag: '🇺🇸' },
  { name: 'White Plains, NY',     key: 'whiteplains', col: 68200, colLow: 59600, colHigh: 71800, state: 'ny', flag: '🇺🇸' },
  { name: 'Huntington, NY',       key: 'huntington_ny', col: 77900, colLow: 66200, colHigh: 77900, state: 'ny', flag: '🇺🇸' },
  { name: 'Corpus Christi, TX',   key: 'corpuschristi', col: 49600, colLow: 46800, colHigh: 50600, state: 'tx', flag: '🇺🇸' },
  { name: 'Lubbock, TX',          key: 'lubbock', col: 47100, colLow: 45800, colHigh: 47800, state: 'tx', flag: '🇺🇸' },
  { name: 'Arlington, TX',        key: 'arlington_tx', col: 53200, colLow: 51200, colHigh: 54000, state: 'tx', flag: '🇺🇸' },
  { name: 'Irving, TX',           key: 'irving', col: 54800, colLow: 52000, colHigh: 55400, state: 'tx', flag: '🇺🇸' },
  { name: 'Garland, TX',          key: 'garland', col: 53900, colLow: 51800, colHigh: 55000, state: 'tx', flag: '🇺🇸' },
  { name: 'Frisco, TX',           key: 'frisco', col: 58800, colLow: 56100, colHigh: 60100, state: 'tx', flag: '🇺🇸' },
  { name: 'McKinney, TX',         key: 'mckinney', col: 55900, colLow: 54800, colHigh: 57100, state: 'tx', flag: '🇺🇸' },
  { name: 'Denton, TX',           key: 'denton', col: 51700, colLow: 48700, colHigh: 53200, state: 'tx', flag: '🇺🇸' },
  { name: 'Waco, TX',             key: 'waco', col: 47700, colLow: 44600, colHigh: 49300, state: 'tx', flag: '🇺🇸' },
  { name: 'Tallahassee, FL',      key: 'tallahassee', col: 50100, colLow: 48100, colHigh: 50700, state: 'fl', flag: '🇺🇸' },
  { name: 'Naples, FL',           key: 'naples_fl', col: 56100, colLow: 40900, colHigh: 76000, state: 'fl', flag: '🇺🇸' },
  { name: 'West Palm Beach, FL',  key: 'westpalmbeach', col: 61100, colLow: 56000, colHigh: 62600, state: 'fl', flag: '🇺🇸' },
  { name: 'Cape Coral, FL',       key: 'capecoral', col: 59900, colLow: 54000, colHigh: 61300, state: 'fl', flag: '🇺🇸' },
  { name: 'Gainesville, FL',      key: 'gainesville_fl', col: 50400, colLow: 47200, colHigh: 52000, state: 'fl', flag: '🇺🇸' },
  { name: 'Fort Myers, FL',       key: 'fortmyers', col: 55800, colLow: 51300, colHigh: 56700, state: 'fl', flag: '🇺🇸' },
  { name: 'Pensacola, FL',        key: 'pensacola', col: 50700, colLow: 47600, colHigh: 52200, state: 'fl', flag: '🇺🇸' },
  { name: 'Bellevue, WA',         key: 'bellevue', col: 66500, colLow: 64300, colHigh: 69000, state: 'wa', flag: '🇺🇸' },
  { name: 'Vancouver, WA',        key: 'vancouver_wa', col: 56300, colLow: 54700, colHigh: 57000, state: 'wa', flag: '🇺🇸' },
  { name: 'Olympia, WA',          key: 'olympia', col: 54900, colLow: 51200, colHigh: 57600, state: 'wa', flag: '🇺🇸' },
  { name: 'Salem, OR',            key: 'salem_or', col: 54000, colLow: 50200, colHigh: 55500, state: 'or', flag: '🇺🇸' },
  { name: 'Bend, OR',             key: 'bend', col: 58900, colLow: 55300, colHigh: 61100, state: 'or', flag: '🇺🇸' },
  { name: 'Aurora, CO',           key: 'aurora_co', col: 57700, colLow: 54900, colHigh: 58900, state: 'co', flag: '🇺🇸' },
  { name: 'Fort Collins, CO',     key: 'fortcollins', col: 54300, colLow: 52700, colHigh: 55200, state: 'co', flag: '🇺🇸' },
  { name: 'Lakewood, CO',         key: 'lakewood_co', col: 56500, colLow: 54500, colHigh: 57300, state: 'co', flag: '🇺🇸' },
  { name: 'Ogden, UT',            key: 'ogden', col: 51400, colLow: 46400, colHigh: 52800, state: 'ut', flag: '🇺🇸' },
  { name: 'St. George, UT',       key: 'stgeorge', col: 56100, colLow: 49100, colHigh: 58700, state: 'ut', flag: '🇺🇸' },
  { name: 'Mesa, AZ',             key: 'mesa', col: 54600, colLow: 52800, colHigh: 55100, state: 'az', flag: '🇺🇸' },
  { name: 'Tempe, AZ',            key: 'tempe', col: 55800, colLow: 53800, colHigh: 56600, state: 'az', flag: '🇺🇸' },
  { name: 'Chandler, AZ',         key: 'chandler', col: 57300, colLow: 55900, colHigh: 58100, state: 'az', flag: '🇺🇸' },
  { name: 'Gilbert, AZ',          key: 'gilbert', col: 59400, colLow: 58100, colHigh: 60400, state: 'az', flag: '🇺🇸' },
  { name: 'Glendale, AZ',         key: 'glendale_az', col: 54800, colLow: 51100, colHigh: 55700, state: 'az', flag: '🇺🇸' },
  { name: 'Henderson, NV',        key: 'henderson', col: 56300, colLow: 54200, colHigh: 57200, state: 'nv', flag: '🇺🇸' },
  { name: 'Augusta, GA',          key: 'augusta_ga', col: 49700, colLow: 46000, colHigh: 50500, state: 'ga', flag: '🇺🇸' },
  { name: 'Athens, GA',           key: 'athens_ga', col: 49500, colLow: 46300, colHigh: 51000, state: 'ga', flag: '🇺🇸' },
  { name: 'Macon, GA',            key: 'macon', col: 47800, colLow: 44800, colHigh: 48900, state: 'ga', flag: '🇺🇸' },
  { name: 'Alpharetta, GA',       key: 'alpharetta', col: 58500, colLow: 54000, colHigh: 61300, state: 'ga', flag: '🇺🇸' },
  { name: 'Durham, NC',           key: 'durham', col: 53600, colLow: 50800, colHigh: 54000, state: 'nc', flag: '🇺🇸' },
  { name: 'Greensboro, NC',       key: 'greensboro', col: 50200, colLow: 46600, colHigh: 50700, state: 'nc', flag: '🇺🇸' },
  { name: 'Winston-Salem, NC',    key: 'winstonsalem', col: 49700, colLow: 45400, colHigh: 50500, state: 'nc', flag: '🇺🇸' },
  { name: 'Wilmington, NC',       key: 'wilmington_nc', col: 52800, colLow: 48900, colHigh: 53800, state: 'nc', flag: '🇺🇸' },
  { name: 'Knoxville, TN',        key: 'knoxville', col: 50100, colLow: 45800, colHigh: 51100, state: 'tn', flag: '🇺🇸' },
  { name: 'Franklin, TN',         key: 'franklin_tn', col: 60000, colLow: 54500, colHigh: 61100, state: 'tn', flag: '🇺🇸' },
  { name: 'Louisville, KY',       key: 'louisville', col: 47500, colLow: 45700, colHigh: 48100, state: 'ky', flag: '🇺🇸' },
  { name: 'Lexington, KY',        key: 'lexington_ky', col: 49500, colLow: 46100, colHigh: 50100, state: 'ky', flag: '🇺🇸' },
  { name: 'Norfolk, VA',          key: 'norfolk', col: 51800, colLow: 48000, colHigh: 52800, state: 'va', flag: '🇺🇸' },
  { name: 'Alexandria, VA',       key: 'alexandria_va', col: 61800, colLow: 59200, colHigh: 62800, state: 'va', flag: '🇺🇸' },
  { name: 'Arlington, VA',        key: 'arlington_va', col: 65600, colLow: 62100, colHigh: 66600, state: 'va', flag: '🇺🇸' },
  { name: 'Charlottesville, VA',  key: 'charlottesville', col: 50900, colLow: 49100, colHigh: 53500, state: 'va', flag: '🇺🇸' },
  { name: 'Greenville, SC',       key: 'greenville_sc', col: 52100, colLow: 47400, colHigh: 53600, state: 'sc', flag: '🇺🇸' },
  { name: 'Myrtle Beach, SC',     key: 'myrtlebeach', col: 50600, colLow: 46400, colHigh: 52500, state: 'sc', flag: '🇺🇸' },
  { name: 'Montgomery, AL',       key: 'montgomery', col: 47700, colLow: 44200, colHigh: 49400, state: 'al', flag: '🇺🇸' },
  { name: 'Mobile, AL',           key: 'mobile', col: 47100, colLow: 44800, colHigh: 48000, state: 'al', flag: '🇺🇸' },
  { name: 'Gulfport, MS',         key: 'gulfport', col: 47300, colLow: 44200, colHigh: 48800, state: 'ms', flag: '🇺🇸' },
  { name: 'Fayetteville, AR',     key: 'fayetteville_ar', col: 45900, colLow: 44300, colHigh: 46500, state: 'ar_us', flag: '🇺🇸' },
  { name: 'Ann Arbor, MI',        key: 'annarbor', col: 53900, colLow: 51800, colHigh: 54800, state: 'mi', flag: '🇺🇸' },
  { name: 'Lansing, MI',          key: 'lansing', col: 45400, colLow: 43700, colHigh: 46500, state: 'mi', flag: '🇺🇸' },
  { name: 'Toledo, OH',           key: 'toledo', col: 43600, colLow: 42600, colHigh: 44600, state: 'oh', flag: '🇺🇸' },
  { name: 'Akron, OH',            key: 'akron', col: 45100, colLow: 43400, colHigh: 46000, state: 'oh', flag: '🇺🇸' },
  { name: 'Dayton, OH',           key: 'dayton', col: 45200, colLow: 42600, colHigh: 46400, state: 'oh', flag: '🇺🇸' },
  { name: 'Springfield, MO',      key: 'springfield_mo', col: 44500, colLow: 42800, colHigh: 45000, state: 'mo', flag: '🇺🇸' },
  { name: 'Columbia, MO',         key: 'columbia_mo', col: 46500, colLow: 43900, colHigh: 47600, state: 'mo', flag: '🇺🇸' },
  { name: 'Green Bay, WI',        key: 'greenbay', col: 47100, colLow: 42900, colHigh: 48300, state: 'wi', flag: '🇺🇸' },
  { name: 'Lincoln, NE',          key: 'lincoln', col: 46200, colLow: 44100, colHigh: 46900, state: 'ne', flag: '🇺🇸' },
  { name: 'Iowa City, IA',        key: 'iowacity', col: 46000, colLow: 42900, colHigh: 47900, state: 'ia', flag: '🇺🇸' },
  { name: 'Cedar Rapids, IA',     key: 'cedarrapids', col: 44400, colLow: 41700, colHigh: 46000, state: 'ia', flag: '🇺🇸' },
  { name: 'Bismarck, ND',         key: 'bismarck', col: 43800, colLow: 40800, colHigh: 46600, state: 'nd', flag: '🇺🇸' },
  { name: 'Edmond, OK',           key: 'edmond', col: 49000, colLow: 46800, colHigh: 50500, state: 'ok', flag: '🇺🇸' },
  { name: 'Overland Park, KS',    key: 'overlandpark', col: 51500, colLow: 49100, colHigh: 52500, state: 'ks', flag: '🇺🇸' },
  { name: 'Topeka, KS',           key: 'topeka', col: 44400, colLow: 42400, colHigh: 45600, state: 'ks', flag: '🇺🇸' },
  { name: 'Worcester, MA',        key: 'worcester', col: 54900, colLow: 50400, colHigh: 56100, state: 'ma', flag: '🇺🇸' },
  { name: 'Springfield, MA',      key: 'springfield_ma', col: 49600, colLow: 43100, colHigh: 53900, state: 'ma', flag: '🇺🇸' },
  { name: 'Stamford, CT',         key: 'stamford', col: 65400, colLow: 58500, colHigh: 68200, state: 'ct', flag: '🇺🇸' },
  { name: 'Greenwich, CT',        key: 'greenwich', col: 73900, colLow: 49800, colHigh: 83100, state: 'ct', flag: '🇺🇸' },
  { name: 'Allentown, PA',        key: 'allentown', col: 51000, colLow: 48300, colHigh: 52200, state: 'pa', flag: '🇺🇸' },
  { name: 'Harrisburg, PA',       key: 'harrisburg', col: 47700, colLow: 44100, colHigh: 50100, state: 'pa', flag: '🇺🇸' },
  { name: 'Manchester, NH',       key: 'manchester_nh', col: 56600, colLow: 51600, colHigh: 58100, state: 'nh', flag: '🇺🇸' },
  { name: 'Bangor, ME',           key: 'bangor', col: 49900, colLow: 44900, colHigh: 51800, state: 'me', flag: '🇺🇸' },
  { name: 'Princeton, NJ',        key: 'princeton', col: 59300, colLow: 50600, colHigh: 73900, state: 'nj', flag: '🇺🇸' },
  { name: 'Atlantic City, NJ',    key: 'atlanticcity', col: 50900, colLow: 42000, colHigh: 56100, state: 'nj', flag: '🇺🇸' },
  { name: 'Trenton, NJ',          key: 'trenton', col: 46900, colLow: 45100, colHigh: 51000, state: 'nj', flag: '🇺🇸' },
  { name: 'Newport, RI',          key: 'newport_ri', col: 60100, colLow: 49600, colHigh: 64800, state: 'ri', flag: '🇺🇸' },
  { name: 'Wilmington, DE',       key: 'wilmington_de', col: 53300, colLow: 47300, colHigh: 54700, state: 'de_us', flag: '🇺🇸' },
  { name: 'Anchorage, AK',        key: 'anchorage', col: 54500, colLow: 52400, colHigh: 55800, state: 'ak', flag: '🇺🇸' },
  { name: 'Fairbanks, AK',        key: 'fairbanks', col: 55600, colLow: 50300, colHigh: 59100, state: 'ak', flag: '🇺🇸' },
  { name: 'Honolulu, HI',         key: 'honolulu', col: 61600, colLow: 56800, colHigh: 63100, state: 'hi', flag: '🇺🇸' },
  { name: 'Kailua-Kona, HI',      key: 'kailuakona', col: 59400, colLow: 54700, colHigh: 62100, state: 'hi', flag: '🇺🇸' },
  { name: 'Billings, MT',         key: 'billings', col: 50200, colLow: 44500, colHigh: 52500, state: 'mt', flag: '🇺🇸' },
  { name: 'Missoula, MT',         key: 'missoula', col: 50500, colLow: 45700, colHigh: 52200, state: 'mt', flag: '🇺🇸' },
  { name: 'Bozeman, MT',          key: 'bozeman', col: 56200, colLow: 51700, colHigh: 58200, state: 'mt', flag: '🇺🇸' },
  { name: 'Cheyenne, WY',         key: 'cheyenne', col: 47800, colLow: 45300, colHigh: 49300, state: 'wy', flag: '🇺🇸' },
  { name: 'Jackson, WY',          key: 'jackson_wy', col: 58500, state: 'wy', flag: '🇺🇸' },
  { name: 'Charleston, WV',       key: 'charleston_wv', col: 44600, colLow: 42200, colHigh: 46700, state: 'wv', flag: '🇺🇸' },
  { name: 'Morgantown, WV',       key: 'morgantown', col: 46100, colLow: 43200, colHigh: 47500, state: 'wv', flag: '🇺🇸' },
  { name: 'Pasadena, CA',        key: 'pasadena_ca', col: 69400, colLow: 59900, colHigh: 72200, state: 'ca', flag: '🇺🇸' },
  { name: 'Berkeley, CA',        key: 'berkeley', col: 62200, colLow: 59200, colHigh: 64000, state: 'ca', flag: '🇺🇸' },
  { name: 'Glendale, CA',        key: 'glendale_ca', col: 64900, colLow: 59400, colHigh: 67200, state: 'ca', flag: '🇺🇸' },
  { name: 'Palo Alto, CA',       key: 'paloalto', col: 77500, colLow: 77300, colHigh: 77500, state: 'ca', flag: '🇺🇸' },
  { name: 'Laredo, TX',          key: 'laredo', col: 45000, colLow: 43400, colHigh: 46200, state: 'tx', flag: '🇺🇸' },
  { name: 'Amarillo, TX',        key: 'amarillo', col: 46200, colLow: 44400, colHigh: 47200, state: 'tx', flag: '🇺🇸' },
  { name: 'Brownsville, TX',     key: 'brownsville', col: 46000, colLow: 41900, colHigh: 47500, state: 'tx', flag: '🇺🇸' },
  { name: 'Killeen, TX',         key: 'killeen', col: 47000, colLow: 45800, colHigh: 48000, state: 'tx', flag: '🇺🇸' },
  { name: 'Midland, TX',         key: 'midland_tx', col: 53800, colLow: 47900, colHigh: 55400, state: 'tx', flag: '🇺🇸' },
  { name: 'Boca Raton, FL',      key: 'bocaraton', col: 67300, colLow: 62200, colHigh: 69100, state: 'fl', flag: '🇺🇸' },
  { name: 'Clearwater, FL',      key: 'clearwater', col: 57500, colLow: 50900, colHigh: 59300, state: 'fl', flag: '🇺🇸' },
  { name: 'Lakeland, FL',        key: 'lakeland', col: 52300, colLow: 48600, colHigh: 53600, state: 'fl', flag: '🇺🇸' },
  { name: 'Everett, WA',         key: 'everett', col: 57500, colLow: 54200, colHigh: 59500, state: 'wa', flag: '🇺🇸' },
  { name: 'Bellingham, WA',      key: 'bellingham', col: 55200, colLow: 51700, colHigh: 57100, state: 'wa', flag: '🇺🇸' },
  { name: 'Hillsboro, OR',       key: 'hillsboro', col: 60100, colLow: 57300, colHigh: 61500, state: 'or', flag: '🇺🇸' },
  { name: 'Idaho Falls, ID',     key: 'idahofalls', col: 48000, colLow: 44600, colHigh: 49600, state: 'id', flag: '🇺🇸' },
  { name: 'Flagstaff, AZ',       key: 'flagstaff', col: 56400, colLow: 51300, colHigh: 58300, state: 'az', flag: '🇺🇸' },
  { name: 'North Las Vegas, NV', key: 'northlasvegas', col: 56500, colLow: 52500, colHigh: 57600, state: 'nv', flag: '🇺🇸' },
  { name: 'Columbus, GA',        key: 'columbus_ga', col: 48200, colLow: 45100, colHigh: 49500, state: 'ga', flag: '🇺🇸' },
  { name: 'Norman, OK',          key: 'norman', col: 45000, colLow: 44100, colHigh: 46200, state: 'ok', flag: '🇺🇸' },
  // ── CHINA
  { name: 'Shanghai, China',      key: 'shanghai',      col: 32000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Beijing, China',       key: 'beijing',       col: 30000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Shenzhen, China',      key: 'shenzhen',      col: 28000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Guangzhou, China',     key: 'guangzhou',     col: 26000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Chengdu, China',       key: 'chengdu',       col: 20000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Hangzhou, China',      key: 'hangzhou',      col: 24000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Nanjing, China',       key: 'nanjing',       col: 22000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Wuhan, China',         key: 'wuhan',         col: 20000,  state: 'cn',     flag: '🇨🇳' },
  { name: "Xi'an, China",         key: 'xian',          col: 18000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Chongqing, China',     key: 'chongqing',     col: 18000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Suzhou, China',        key: 'suzhou',        col: 22000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Tianjin, China',       key: 'tianjin',       col: 20000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Qingdao, China',       key: 'qingdao',       col: 20000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Xiamen, China',        key: 'xiamen',        col: 22000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Kunming, China',       key: 'kunming',       col: 16000,  state: 'cn',     flag: '🇨🇳' },
  { name: 'Sanya, China',         key: 'sanya',         col: 20000,  state: 'cn',     flag: '🇨🇳' },
  // ── INDIA
  { name: 'Mumbai, India',        key: 'mumbai',        col: 12000,  state: 'in_ind', flag: '🇮🇳' },
  { name: 'Bangalore, India',     key: 'bangalore',     col: 11000,  state: 'in_ind', flag: '🇮🇳' },
  { name: 'Delhi, India',         key: 'delhi',         col: 10000,  state: 'in_ind', flag: '🇮🇳' },
  { name: 'Hyderabad, India',     key: 'hyderabad',     col: 10000,  state: 'in_ind', flag: '🇮🇳' },
  { name: 'Chennai, India',       key: 'chennai',       col: 10000,  state: 'in_ind', flag: '🇮🇳' },
  { name: 'Pune, India',          key: 'pune',          col: 9000,   state: 'in_ind', flag: '🇮🇳' },
  { name: 'Kolkata, India',       key: 'kolkata',       col: 8000,   state: 'in_ind', flag: '🇮🇳' },
  { name: 'Ahmedabad, India',     key: 'ahmedabad',     col: 8000,   state: 'in_ind', flag: '🇮🇳' },
  { name: 'Jaipur, India',        key: 'jaipur',        col: 7000,   state: 'in_ind', flag: '🇮🇳' },
  { name: 'Goa, India',           key: 'goa',           col: 10000,  state: 'in_ind', flag: '🇮🇳' },
  // ── SOUTHEAST ASIA
  { name: 'Singapore',            key: 'singapore',     col: 72000,  state: 'sg',     flag: '🇸🇬' },
  { name: 'Bangkok, Thailand',    key: 'bangkok',       col: 22000,  state: 'th',     flag: '🇹🇭' },
  { name: 'Chiang Mai, Thailand', key: 'chiangmai',     col: 16000,  state: 'th',     flag: '🇹🇭' },
  { name: 'Phuket, Thailand',     key: 'phuket',        col: 20000,  state: 'th',     flag: '🇹🇭' },
  { name: 'Pattaya, Thailand',    key: 'pattaya',       col: 16000,  state: 'th',     flag: '🇹🇭' },
  { name: 'Kuala Lumpur, Malaysia',key:'kualalumpur',   col: 20000,  state: 'my',     flag: '🇲🇾' },
  { name: 'Penang, Malaysia',     key: 'penang',        col: 16000,  state: 'my',     flag: '🇲🇾' },
  { name: 'Ho Chi Minh City, Vietnam', key: 'hcmc',     col: 12000,  state: 'vn',     flag: '🇻🇳' },
  { name: 'Hanoi, Vietnam',       key: 'hanoi',         col: 12000,  state: 'vn',     flag: '🇻🇳' },
  { name: 'Da Nang, Vietnam',     key: 'danang',        col: 10000,  state: 'vn',     flag: '🇻🇳' },
  { name: 'Bali, Indonesia',      key: 'bali',          col: 14000,  state: 'id_idn', flag: '🇮🇩' },
  { name: 'Jakarta, Indonesia',   key: 'jakarta',       col: 16000,  state: 'id_idn', flag: '🇮🇩' },
  { name: 'Manila, Philippines',  key: 'manila',        col: 12000,  state: 'ph',     flag: '🇵🇭' },
  { name: 'Cebu, Philippines',    key: 'cebu',          col: 10000,  state: 'ph',     flag: '🇵🇭' },
  { name: 'Phnom Penh, Cambodia', key: 'phnompenh',     col: 10000,  state: 'kh',     flag: '🇰🇭' },
  // ── JAPAN & KOREA
  { name: 'Tokyo, Japan',         key: 'tokyo',         col: 58000,  state: 'jp',     flag: '🇯🇵' },
  { name: 'Osaka, Japan',         key: 'osaka',         col: 48000,  state: 'jp',     flag: '🇯🇵' },
  { name: 'Kyoto, Japan',         key: 'kyoto',         col: 46000,  state: 'jp',     flag: '🇯🇵' },
  { name: 'Fukuoka, Japan',       key: 'fukuoka',       col: 40000,  state: 'jp',     flag: '🇯🇵' },
  { name: 'Sapporo, Japan',       key: 'sapporo',       col: 38000,  state: 'jp',     flag: '🇯🇵' },
  { name: 'Nagoya, Japan',        key: 'nagoya',        col: 44000,  state: 'jp',     flag: '🇯🇵' },
  { name: 'Seoul, South Korea',   key: 'seoul',         col: 38000,  state: 'kr',     flag: '🇰🇷' },
  { name: 'Busan, South Korea',   key: 'busan',         col: 32000,  state: 'kr',     flag: '🇰🇷' },
  { name: 'Taipei, Taiwan',       key: 'taipei',        col: 28000,  state: 'tw',     flag: '🇹🇼' },
  { name: 'Hong Kong',            key: 'hongkong',      col: 80000,  state: 'hk',     flag: '🇭🇰' },
  { name: 'Macau',                key: 'macau',         col: 36000,  state: 'hk',     flag: '🇲🇴' },
  // ── MIDDLE EAST
  { name: 'Dubai, UAE',           key: 'dubai',         col: 60000,  state: 'ae',     flag: '🇦🇪' },
  { name: 'Abu Dhabi, UAE',       key: 'abudhabi',      col: 64000,  state: 'ae',     flag: '🇦🇪' },
  { name: 'Riyadh, Saudi Arabia', key: 'riyadh',        col: 36000,  state: 'sa',     flag: '🇸🇦' },
  { name: 'Doha, Qatar',          key: 'doha',          col: 44000,  state: 'qa',     flag: '🇶🇦' },
  { name: 'Tel Aviv, Israel',     key: 'telaviv',       col: 52000,  state: 'il_isr', flag: '🇮🇱' },
  { name: 'Istanbul, Turkey',     key: 'istanbul',      col: 18000,  state: 'tr',     flag: '🇹🇷' },
  { name: 'Ankara, Turkey',       key: 'ankara',        col: 14000,  state: 'tr',     flag: '🇹🇷' },
  // ── UK
  { name: 'London, UK',           key: 'london',        col: 80000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Manchester, UK',       key: 'manchester',    col: 54000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Edinburgh, UK',        key: 'edinburgh',     col: 52000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Bristol, UK',          key: 'bristol',       col: 52000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Birmingham, UK',       key: 'birmingham_uk', col: 48000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Leeds, UK',            key: 'leeds',         col: 46000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Glasgow, UK',          key: 'glasgow',       col: 44000,  state: 'uk',     flag: '🇬🇧' },
  { name: 'Brighton, UK',         key: 'brighton',      col: 54000,  state: 'uk',     flag: '🇬🇧' },
  // ── WESTERN EUROPE
  { name: 'Paris, France',        key: 'paris',         col: 68000,  state: 'fr',     flag: '🇫🇷' },
  { name: 'Lyon, France',         key: 'lyon',          col: 48000,  state: 'fr',     flag: '🇫🇷' },
  { name: 'Nice, France',         key: 'nice',          col: 52000,  state: 'fr',     flag: '🇫🇷' },
  { name: 'Bordeaux, France',     key: 'bordeaux',      col: 44000,  state: 'fr',     flag: '🇫🇷' },
  { name: 'Berlin, Germany',      key: 'berlin',        col: 48000,  state: 'de',     flag: '🇩🇪' },
  { name: 'Munich, Germany',      key: 'munich',        col: 62000,  state: 'de',     flag: '🇩🇪' },
  { name: 'Hamburg, Germany',     key: 'hamburg',       col: 52000,  state: 'de',     flag: '🇩🇪' },
  { name: 'Frankfurt, Germany',   key: 'frankfurt',     col: 54000,  state: 'de',     flag: '🇩🇪' },
  { name: 'Cologne, Germany',     key: 'cologne',       col: 48000,  state: 'de',     flag: '🇩🇪' },
  { name: 'Düsseldorf, Germany',  key: 'dusseldorf',    col: 50000,  state: 'de',     flag: '🇩🇪' },
  { name: 'Amsterdam, Netherlands',key:'amsterdam',     col: 62000,  state: 'nl',     flag: '🇳🇱' },
  { name: 'Rotterdam, Netherlands',key:'rotterdam',     col: 54000,  state: 'nl',     flag: '🇳🇱' },
  { name: 'Barcelona, Spain',     key: 'barcelona',     col: 44000,  state: 'es',     flag: '🇪🇸' },
  { name: 'Madrid, Spain',        key: 'madrid',        col: 42000,  state: 'es',     flag: '🇪🇸' },
  { name: 'Valencia, Spain',      key: 'valencia',      col: 36000,  state: 'es',     flag: '🇪🇸' },
  { name: 'Seville, Spain',       key: 'seville',       col: 34000,  state: 'es',     flag: '🇪🇸' },
  { name: 'Málaga, Spain',        key: 'malaga',        col: 32000,  state: 'es',     flag: '🇪🇸' },
  { name: 'Lisbon, Portugal',     key: 'lisbon',        col: 36000,  state: 'pt',     flag: '🇵🇹' },
  { name: 'Porto, Portugal',      key: 'porto',         col: 32000,  state: 'pt',     flag: '🇵🇹' },
  { name: 'Faro, Portugal',       key: 'faro',          col: 28000,  state: 'pt',     flag: '🇵🇹' },
  { name: 'Dublin, Ireland',      key: 'dublin',        col: 68000,  state: 'ie',     flag: '🇮🇪' },
  { name: 'Cork, Ireland',        key: 'cork',          col: 52000,  state: 'ie',     flag: '🇮🇪' },
  { name: 'Zurich, Switzerland',  key: 'zurich',        col: 100000, state: 'ch',     flag: '🇨🇭' },
  { name: 'Geneva, Switzerland',  key: 'geneva',        col: 98000,  state: 'ch',     flag: '🇨🇭' },
  { name: 'Basel, Switzerland',   key: 'basel',         col: 90000,  state: 'ch',     flag: '🇨🇭' },
  { name: 'Stockholm, Sweden',    key: 'stockholm',     col: 58000,  state: 'se',     flag: '🇸🇪' },
  { name: 'Gothenburg, Sweden',   key: 'gothenburg',    col: 52000,  state: 'se',     flag: '🇸🇪' },
  { name: 'Malmö, Sweden',        key: 'malmo',         col: 48000,  state: 'se',     flag: '🇸🇪' },
  { name: 'Copenhagen, Denmark',  key: 'copenhagen',    col: 62000,  state: 'dk',     flag: '🇩🇰' },
  { name: 'Oslo, Norway',         key: 'oslo',          col: 72000,  state: 'no',     flag: '🇳🇴' },
  { name: 'Bergen, Norway',       key: 'bergen',        col: 64000,  state: 'no',     flag: '🇳🇴' },
  { name: 'Helsinki, Finland',    key: 'helsinki',      col: 56000,  state: 'fi',     flag: '🇫🇮' },
  { name: 'Vienna, Austria',      key: 'vienna',        col: 50000,  state: 'at',     flag: '🇦🇹' },
  { name: 'Graz, Austria',        key: 'graz',          col: 44000,  state: 'at',     flag: '🇦🇹' },
  { name: 'Brussels, Belgium',    key: 'brussels',      col: 58000,  state: 'be',     flag: '🇧🇪' },
  { name: 'Antwerp, Belgium',     key: 'antwerp',       col: 52000,  state: 'be',     flag: '🇧🇪' },
  { name: 'Milan, Italy',         key: 'milan',         col: 48000,  state: 'it',     flag: '🇮🇹' },
  { name: 'Rome, Italy',          key: 'rome',          col: 44000,  state: 'it',     flag: '🇮🇹' },
  { name: 'Florence, Italy',      key: 'florence',      col: 42000,  state: 'it',     flag: '🇮🇹' },
  { name: 'Naples, Italy',        key: 'naples',        col: 34000,  state: 'it',     flag: '🇮🇹' },
  { name: 'Athens, Greece',       key: 'athens',        col: 28000,  state: 'gr',     flag: '🇬🇷' },
  { name: 'Thessaloniki, Greece', key: 'thessaloniki',  col: 24000,  state: 'gr',     flag: '🇬🇷' },
  // ── EASTERN EUROPE
  { name: 'Prague, Czech Republic',  key: 'prague',     col: 30000,  state: 'cz',     flag: '🇨🇿' },
  { name: 'Brno, Czech Republic',    key: 'brno',       col: 26000,  state: 'cz',     flag: '🇨🇿' },
  { name: 'Warsaw, Poland',          key: 'warsaw',     col: 28000,  state: 'pl',     flag: '🇵🇱' },
  { name: 'Kraków, Poland',          key: 'krakow',     col: 24000,  state: 'pl',     flag: '🇵🇱' },
  { name: 'Budapest, Hungary',       key: 'budapest',   col: 26000,  state: 'hu',     flag: '🇭🇺' },
  { name: 'Bucharest, Romania',      key: 'bucharest',  col: 20000,  state: 'ro',     flag: '🇷🇴' },
  { name: 'Sofia, Bulgaria',         key: 'sofia',      col: 18000,  state: 'bg',     flag: '🇧🇬' },
  { name: 'Belgrade, Serbia',        key: 'belgrade',   col: 18000,  state: 'rs',     flag: '🇷🇸' },
  { name: 'Zagreb, Croatia',         key: 'zagreb',     col: 24000,  state: 'hr',     flag: '🇭🇷' },
  { name: 'Ljubljana, Slovenia',     key: 'ljubljana',  col: 28000,  state: 'si',     flag: '🇸🇮' },
  { name: 'Tallinn, Estonia',        key: 'tallinn',    col: 28000,  state: 'ee',     flag: '🇪🇪' },
  { name: 'Riga, Latvia',            key: 'riga',       col: 24000,  state: 'lv',     flag: '🇱🇻' },
  { name: 'Vilnius, Lithuania',      key: 'vilnius',    col: 24000,  state: 'lt',     flag: '🇱🇹' },
  // ── CANADA
  { name: 'Toronto, Canada',         key: 'toronto',    col: 68000,  state: 'ca_on',  flag: '🇨🇦' },
  { name: 'Vancouver, Canada',       key: 'vancouver',  col: 72000,  state: 'ca_bc',  flag: '🇨🇦' },
  { name: 'Montreal, Canada',        key: 'montreal',   col: 52000,  state: 'ca_qc',  flag: '🇨🇦' },
  { name: 'Calgary, Canada',         key: 'calgary',    col: 56000,  state: 'ca_ab',  flag: '🇨🇦' },
  { name: 'Ottawa, Canada',          key: 'ottawa',     col: 56000,  state: 'ca_on',  flag: '🇨🇦' },
  { name: 'Edmonton, Canada',        key: 'edmonton',   col: 52000,  state: 'ca_ab',  flag: '🇨🇦' },
  { name: 'Winnipeg, Canada',        key: 'winnipeg',   col: 46000,  state: 'ca_mb',  flag: '🇨🇦' },
  { name: 'Halifax, Canada',         key: 'halifax',    col: 44000,  state: 'ca_ns',  flag: '🇨🇦' },
  // ── AUSTRALIA & NZ
  { name: 'Sydney, Australia',       key: 'sydney',     col: 72000,  state: 'au',     flag: '🇦🇺' },
  { name: 'Melbourne, Australia',    key: 'melbourne',  col: 66000,  state: 'au',     flag: '🇦🇺' },
  { name: 'Brisbane, Australia',     key: 'brisbane',   col: 58000,  state: 'au',     flag: '🇦🇺' },
  { name: 'Perth, Australia',        key: 'perth',      col: 60000,  state: 'au',     flag: '🇦🇺' },
  { name: 'Adelaide, Australia',     key: 'adelaide',   col: 54000,  state: 'au',     flag: '🇦🇺' },
  { name: 'Gold Coast, Australia',   key: 'goldcoast',  col: 58000,  state: 'au',     flag: '🇦🇺' },
  { name: 'Auckland, New Zealand',   key: 'auckland',   col: 60000,  state: 'nz',     flag: '🇳🇿' },
  { name: 'Wellington, New Zealand', key: 'wellington', col: 56000,  state: 'nz',     flag: '🇳🇿' },
  { name: 'Christchurch, New Zealand',key:'christchurch',col:48000,  state: 'nz',     flag: '🇳🇿' },
  // ── LATIN AMERICA
  { name: 'Mexico City, Mexico',     key: 'mexicocity',      col: 18000, state: 'mx',     flag: '🇲🇽' },
  { name: 'Guadalajara, Mexico',     key: 'guadalajara',     col: 14000, state: 'mx',     flag: '🇲🇽' },
  { name: 'Monterrey, Mexico',       key: 'monterrey',       col: 16000, state: 'mx',     flag: '🇲🇽' },
  { name: 'Playa del Carmen, Mexico',key: 'playadelcarmen',  col: 16000, state: 'mx',     flag: '🇲🇽' },
  { name: 'Bogotá, Colombia',        key: 'bogota',          col: 12000, state: 'co_col', flag: '🇨🇴' },
  { name: 'Medellín, Colombia',      key: 'medellin',        col: 10000, state: 'co_col', flag: '🇨🇴' },
  { name: 'Cartagena, Colombia',     key: 'cartagena',       col: 10000, state: 'co_col', flag: '🇨🇴' },
  { name: 'Buenos Aires, Argentina', key: 'buenosaires',     col: 8000,  state: 'ar_lat', flag: '🇦🇷' },
  { name: 'São Paulo, Brazil',       key: 'saopaulo',        col: 14000, state: 'br',     flag: '🇧🇷' },
  { name: 'Rio de Janeiro, Brazil',  key: 'rio',             col: 13000, state: 'br',     flag: '🇧🇷' },
  { name: 'Florianópolis, Brazil',   key: 'florianopolis',   col: 12000, state: 'br',     flag: '🇧🇷' },
  { name: 'Santiago, Chile',         key: 'santiago',        col: 16000, state: 'cl',     flag: '🇨🇱' },
  { name: 'Lima, Peru',              key: 'lima',            col: 10000, state: 'pe',     flag: '🇵🇪' },
  { name: 'Montevideo, Uruguay',     key: 'montevideo',      col: 16000, state: 'uy',     flag: '🇺🇾' },
  { name: 'Panama City, Panama',     key: 'panamacity',      col: 18000, state: 'pa_pan', flag: '🇵🇦' },
  { name: 'San José, Costa Rica',    key: 'sanjose_cr',      col: 16000, state: 'cr',     flag: '🇨🇷' },
  // ── AFRICA
  { name: 'Cape Town, South Africa', key: 'capetown',     col: 18000, state: 'za',     flag: '🇿🇦' },
  { name: 'Johannesburg, South Africa',key:'johannesburg',col: 16000, state: 'za',     flag: '🇿🇦' },
  { name: 'Nairobi, Kenya',          key: 'nairobi',      col: 12000, state: 'ke',     flag: '🇰🇪' },
  { name: 'Lagos, Nigeria',          key: 'lagos',        col: 12000, state: 'ng',     flag: '🇳🇬' },
  { name: 'Accra, Ghana',            key: 'accra',        col: 10000, state: 'gh',     flag: '🇬🇭' },
  { name: 'Cairo, Egypt',            key: 'cairo',        col: 10000, state: 'eg',     flag: '🇪🇬' },
  { name: 'Casablanca, Morocco',     key: 'casablanca',   col: 12000, state: 'ma_mar', flag: '🇲🇦' },
  // ── DIGITAL NOMAD HOTSPOTS
  { name: 'Tbilisi, Georgia',        key: 'tbilisi',      col: 12000, state: 'ge',     flag: '🇬🇪' },
  { name: 'Split, Croatia',          key: 'split',        col: 22000, state: 'hr',     flag: '🇭🇷' },
  { name: 'Madeira, Portugal',       key: 'madeira',      col: 26000, state: 'pt',     flag: '🇵🇹' },
  { name: 'Canary Islands, Spain',   key: 'canary',       col: 28000, state: 'es',     flag: '🇪🇸' },
];

// ─────────────────────────────────────────────────────────────────────────────
// TAX RATES
// ─────────────────────────────────────────────────────────────────────────────

export interface TaxInfo { rate: number; label: string; }

export const STATE_TAX: Record<string, TaxInfo> = {
  // Custom city — sentinel used when the user enters a city we don't have in the
  // database. We deliberately do NOT assume a tax jurisdiction here; the income
  // screen forces take-home mode so we never invent a tax estimate.
  custom: { rate: 0, label: 'Custom city — tax estimate unavailable, enter take-home directly' },
  // US – no income tax
  tx:  { rate: 0,      label: 'Texas — no state income tax' },
  fl:  { rate: 0,      label: 'Florida — no state income tax' },
  tn:  { rate: 0,      label: 'Tennessee — no state income tax' },
  wa:  { rate: 0,      label: 'Washington — no state income tax' },
  nv:  { rate: 0,      label: 'Nevada — no state income tax' },
  ak:  { rate: 0,      label: 'Alaska — no state income tax' },
  wy:  { rate: 0,      label: 'Wyoming — no state income tax' },
  sd:  { rate: 0,      label: 'South Dakota — no state income tax' },
  nh:  { rate: 0,      label: 'New Hampshire — no income tax on wages' },
  // US – flat / effective
  co:  { rate: 0.044,  label: 'Colorado — 4.40% flat' },
  nc:  { rate: 0.045,  label: 'North Carolina — 4.50% flat' },
  ma:  { rate: 0.05,   label: 'Massachusetts — 5.00% flat' },
  ga:  { rate: 0.0549, label: 'Georgia — 5.49% flat' },
  mi:  { rate: 0.0425, label: 'Michigan — 4.25% flat' },
  in_us:{ rate: 0.0305,label: 'Indiana — 3.05% flat' },
  az:  { rate: 0.025,  label: 'Arizona — 2.50% flat' },
  ut:  { rate: 0.0465, label: 'Utah — 4.65% flat' },
  pa:  { rate: 0.0307, label: 'Pennsylvania — 3.07% flat' },
  il:  { rate: 0.0495, label: 'Illinois — 4.95% flat' },
  ms:  { rate: 0.05,   label: 'Mississippi — 5.0% flat' },
  or:  { rate: 0.0875, label: 'Oregon — ~8.75% effective' },
  ca:  { rate: 0.072,  label: 'California — ~7.20% effective' },
  nyc: { rate: 0.1021, label: 'NY State + NYC city tax' },
  ny:  { rate: 0.0633, label: 'New York State — ~6.33% effective' },
  mn:  { rate: 0.0685, label: 'Minnesota — ~6.85% effective' },
  oh:  { rate: 0.0399, label: 'Ohio — ~3.99% effective' },
  mo:  { rate: 0.048,  label: 'Missouri — ~4.80% effective' },
  wi:  { rate: 0.065,  label: 'Wisconsin — ~6.50% effective' },
  ne:  { rate: 0.0584, label: 'Nebraska — ~5.84% effective' },
  dc:  { rate: 0.085,  label: 'Washington DC — ~8.50% effective' },
  md:  { rate: 0.06,   label: 'Maryland — ~6.00% effective' },
  ct:  { rate: 0.065,  label: 'Connecticut — ~6.50% effective' },
  ri:  { rate: 0.0599, label: 'Rhode Island — ~5.99% effective' },
  va:  { rate: 0.0575, label: 'Virginia — 5.75% top rate' },
  la:  { rate: 0.0425, label: 'Louisiana — ~4.25% effective' },
  id:  { rate: 0.058,  label: 'Idaho — ~5.80% effective' },
  nm:  { rate: 0.049,  label: 'New Mexico — ~4.90% effective' },
  sc:  { rate: 0.07,   label: 'South Carolina — ~7.0% effective' },
  al:  { rate: 0.05,   label: 'Alabama — ~5.0% effective' },
  ar_us:{ rate:0.047,  label: 'Arkansas — ~4.7% effective' },
  ia:  { rate: 0.06,   label: 'Iowa — ~6.0% effective' },
  nd:  { rate: 0.027,  label: 'North Dakota — ~2.7% effective' },
  ok:  { rate: 0.045,  label: 'Oklahoma — ~4.5% effective' },
  ks:  { rate: 0.053,  label: 'Kansas — ~5.3% effective' },
  vt:  { rate: 0.066,  label: 'Vermont — ~6.6% effective' },
  me:  { rate: 0.072,  label: 'Maine — ~7.2% effective' },
  nj:  { rate: 0.063,  label: 'New Jersey — ~6.3% effective' },
  ky:  { rate: 0.045,  label: 'Kentucky — 4.50% flat' },
  de_us:{ rate: 0.066,  label: 'Delaware — ~6.6% effective' },
  hi:  { rate: 0.075,  label: 'Hawaii — ~7.5% effective' },
  mt:  { rate: 0.059,  label: 'Montana — ~5.9% effective' },
  wv:  { rate: 0.0512, label: 'West Virginia — ~5.12% effective' },
  // International
  ae:  { rate: 0,      label: 'UAE — no personal income tax' },
  sa:  { rate: 0,      label: 'Saudi Arabia — no personal income tax' },
  qa:  { rate: 0,      label: 'Qatar — no personal income tax' },
  jp:  { rate: 0.18,   label: 'Japan — ~18% effective' },
  uk:  { rate: 0.20,   label: 'UK — ~20% effective' },
  de:  { rate: 0.22,   label: 'Germany — ~22% effective' },
  nl:  { rate: 0.25,   label: 'Netherlands — ~25% effective' },
  fr:  { rate: 0.24,   label: 'France — ~24% effective' },
  es:  { rate: 0.18,   label: 'Spain — ~18% effective' },
  pt:  { rate: 0.15,   label: 'Portugal — ~15% effective' },
  ie:  { rate: 0.20,   label: 'Ireland — ~20% effective' },
  ch:  { rate: 0.20,   label: 'Switzerland — ~20% effective' },
  se:  { rate: 0.30,   label: 'Sweden — ~30% effective' },
  dk:  { rate: 0.35,   label: 'Denmark — ~35% effective' },
  no:  { rate: 0.28,   label: 'Norway — ~28% effective' },
  at:  { rate: 0.22,   label: 'Austria — ~22% effective' },
  fi:  { rate: 0.30,   label: 'Finland — ~30% effective' },
  be:  { rate: 0.32,   label: 'Belgium — ~32% effective' },
  it:  { rate: 0.25,   label: 'Italy — ~25% effective' },
  gr:  { rate: 0.22,   label: 'Greece — ~22% effective' },
  cz:  { rate: 0.15,   label: 'Czech Republic — 15% flat' },
  pl:  { rate: 0.12,   label: 'Poland — 12% lower bracket' },
  hu:  { rate: 0.15,   label: 'Hungary — 15% flat' },
  ro:  { rate: 0.10,   label: 'Romania — 10% flat' },
  bg:  { rate: 0.10,   label: 'Bulgaria — 10% flat' },
  rs:  { rate: 0.10,   label: 'Serbia — 10% flat' },
  hr:  { rate: 0.20,   label: 'Croatia — ~20% effective' },
  si:  { rate: 0.20,   label: 'Slovenia — ~20% effective' },
  ee:  { rate: 0.20,   label: 'Estonia — 20% flat' },
  lv:  { rate: 0.20,   label: 'Latvia — 20% flat' },
  lt:  { rate: 0.20,   label: 'Lithuania — 20% flat' },
  sg:  { rate: 0.10,   label: 'Singapore — ~10% effective' },
  hk:  { rate: 0.12,   label: 'Hong Kong — ~12% effective' },
  au:  { rate: 0.22,   label: 'Australia — ~22% effective' },
  nz:  { rate: 0.20,   label: 'New Zealand — ~20% effective' },
  th:  { rate: 0.05,   label: 'Thailand — ~5% effective' },
  id_idn:{ rate: 0.05, label: 'Indonesia — ~5% effective' },
  my:  { rate: 0.08,   label: 'Malaysia — ~8% effective' },
  vn:  { rate: 0.10,   label: 'Vietnam — ~10% effective' },
  ph:  { rate: 0.15,   label: 'Philippines — ~15% effective' },
  kh:  { rate: 0.20,   label: 'Cambodia — 20% flat' },
  kr:  { rate: 0.15,   label: 'South Korea — ~15% effective' },
  tw:  { rate: 0.12,   label: 'Taiwan — ~12% effective' },
  in_ind:{ rate: 0.15, label: 'India — ~15% effective' },
  cn:  { rate: 0.06,   label: 'China — ~6% effective' },
  il_isr:{ rate: 0.20, label: 'Israel — ~20% effective' },
  tr:  { rate: 0.20,   label: 'Turkey — ~20% effective' },
  ca_on:{ rate: 0.113, label: 'Ontario — ~11.3% effective' },
  ca_bc:{ rate: 0.102, label: 'British Columbia — ~10.2% effective' },
  ca_qc:{ rate: 0.149, label: 'Quebec — ~14.9% effective' },
  ca_ab:{ rate: 0.10,  label: 'Alberta — ~10.0% effective' },
  ca_mb:{ rate: 0.108, label: 'Manitoba — ~10.8% effective' },
  ca_ns:{ rate: 0.135, label: 'Nova Scotia — ~13.5% effective' },
  mx:  { rate: 0.07,   label: 'Mexico — ~7% effective' },
  co_col:{ rate: 0.08, label: 'Colombia — ~8% effective' },
  ar_lat:{ rate: 0.10, label: 'Argentina — ~10% effective' },
  br:  { rate: 0.18,   label: 'Brazil — ~18% effective' },
  cl:  { rate: 0.10,   label: 'Chile — ~10% effective' },
  pe:  { rate: 0.15,   label: 'Peru — ~15% effective' },
  uy:  { rate: 0.12,   label: 'Uruguay — ~12% effective' },
  pa_pan:{ rate: 0.10, label: 'Panama — ~10% effective' },
  cr:  { rate: 0.15,   label: 'Costa Rica — ~15% effective' },
  za:  { rate: 0.18,   label: 'South Africa — ~18% effective' },
  ke:  { rate: 0.20,   label: 'Kenya — ~20% effective' },
  ng:  { rate: 0.15,   label: 'Nigeria — ~15% effective' },
  gh:  { rate: 0.15,   label: 'Ghana — ~15% effective' },
  eg:  { rate: 0.15,   label: 'Egypt — ~15% effective' },
  ma_mar:{ rate: 0.15, label: 'Morocco — ~15% effective' },
  ge:  { rate: 0.20,   label: 'Georgia — 20% flat' },
};

const US_INTL = new Set([
  'jp','uk','de','nl','fr','es','pt','ie','ch','se','dk','no','at','fi','be','it','gr',
  'cz','pl','hu','ro','bg','rs','hr','si','ee','lv','lt',
  'sg','hk','au','nz','th','id_idn','my','vn','ph','kh','kr','tw','in_ind','cn',
  'il_isr','tr','ae','sa','qa',
  'ca_on','ca_bc','ca_qc','ca_ab','ca_mb','ca_ns',
  'mx','co_col','ar_lat','br','cl','pe','uy','pa_pan','cr',
  'za','ke','ng','gh','eg','ma_mar','ge',
]);
export function isUS(stateKey: string) { return !US_INTL.has(stateKey); }

export const TAX_COUNTRIES: { value: string; label: string; flag: string }[] = [
  { value: "us",  label: "United States",  flag: "🇺🇸" },
  { value: "uk",  label: "United Kingdom", flag: "🇬🇧" },
  { value: "ca",  label: "Canada",         flag: "🇨🇦" },
  { value: "au",  label: "Australia",      flag: "🇦🇺" },
  { value: "nz",  label: "New Zealand",    flag: "🇳🇿" },
  { value: "sg",  label: "Singapore",      flag: "🇸🇬" },
  { value: "ae",  label: "UAE",            flag: "🇦🇪" },
  { value: "de",  label: "Germany",        flag: "🇩🇪" },
  { value: "fr",  label: "France",         flag: "🇫🇷" },
  { value: "nl",  label: "Netherlands",    flag: "🇳🇱" },
  { value: "jp",  label: "Japan",          flag: "🇯🇵" },
  { value: "mx",  label: "Mexico",         flag: "🇲🇽" },
];

export const TAX_US_STATES: { value: string; label: string }[] = [
  { value: "al", label: "Alabama" }, { value: "ak", label: "Alaska" },
  { value: "az", label: "Arizona" }, { value: "ar_us", label: "Arkansas" },
  { value: "ca", label: "California" }, { value: "co", label: "Colorado" },
  { value: "ct", label: "Connecticut" }, { value: "de_us", label: "Delaware" },
  { value: "fl", label: "Florida" }, { value: "ga", label: "Georgia" },
  { value: "hi", label: "Hawaii" }, { value: "id", label: "Idaho" },
  { value: "il", label: "Illinois" }, { value: "in_us", label: "Indiana" },
  { value: "ia", label: "Iowa" }, { value: "ks", label: "Kansas" },
  { value: "ky", label: "Kentucky" }, { value: "la", label: "Louisiana" },
  { value: "me", label: "Maine" }, { value: "md", label: "Maryland" },
  { value: "ma", label: "Massachusetts" }, { value: "mi", label: "Michigan" },
  { value: "mn", label: "Minnesota" }, { value: "ms", label: "Mississippi" },
  { value: "mo", label: "Missouri" }, { value: "mt", label: "Montana" },
  { value: "ne", label: "Nebraska" }, { value: "nv", label: "Nevada" },
  { value: "nh", label: "New Hampshire" }, { value: "nj", label: "New Jersey" },
  { value: "nm", label: "New Mexico" }, { value: "nyc", label: "New York (NYC)" },
  { value: "ny", label: "New York (state)" }, { value: "nc", label: "North Carolina" },
  { value: "nd", label: "North Dakota" }, { value: "oh", label: "Ohio" },
  { value: "ok", label: "Oklahoma" }, { value: "or", label: "Oregon" },
  { value: "pa", label: "Pennsylvania" }, { value: "ri", label: "Rhode Island" },
  { value: "sc", label: "South Carolina" }, { value: "sd", label: "South Dakota" },
  { value: "tn", label: "Tennessee" }, { value: "tx", label: "Texas" },
  { value: "ut", label: "Utah" }, { value: "vt", label: "Vermont" },
  { value: "va", label: "Virginia" }, { value: "wa", label: "Washington" },
  { value: "dc", label: "Washington D.C." }, { value: "wv", label: "West Virginia" },
  { value: "wi", label: "Wisconsin" }, { value: "wy", label: "Wyoming" },
];

export const TAX_CA_PROVINCES: { value: string; label: string }[] = [
  { value: "ca_on", label: "Ontario" }, { value: "ca_bc", label: "British Columbia" },
  { value: "ca_qc", label: "Quebec" }, { value: "ca_ab", label: "Alberta" },
  { value: "ca_mb", label: "Manitoba" }, { value: "ca_ns", label: "Nova Scotia" },
];


// `lib/fire/strategies/traditional.ts` and `lib/fire/tax/*`). This module is
// the city/tax dataset only — keeping data and engine separate is what makes
// the planner swappable without touching the wizard.
