/**
 * US prices since the net-worth survey year, for lib/net-worth-compare.ts.
 *
 * GENERATED by scripts/build-net-worth-inflation.mjs from the BLS consumer
 * price index (CUUR0000SA0: CPI-U, all items, US city average, not seasonally
 * adjusted). Do not edit by hand. August 2026: 334.98; 2022
 * annual average: 292.655.
 */
import type { InflationAdjustment } from './net-worth-compare'

export const NET_WORTH_INFLATION: InflationAdjustment | null = {"factor":1.1446,"through":"August 2026"}
