// Generated by scripts/build-sp500-history.mjs — do not edit by hand.
// S&P 500 total return (dividends reinvested), from Shiller's monthly data
// and BLS CPI-U, through December 2025. Dividends after 2023-06 are
// held at the last reported level, which errs cautious.

export interface Sp500Period {
  id: string
  label: string
  /** Why this start year is used. */
  why: string
  from: number
  to: number
  /** Average yearly return, compounded, before inflation. */
  nominalPct: number
  /** The same after inflation: what the freedom date uses. */
  realPct: number
  /** Average inflation over the same years. */
  inflationPct: number
  /** Share of all 30-year stretches since 1928 that did at least this well. */
  beatShare: number
}

export const SP500_HISTORY = {
  "through": 2025,
  "windowYears": 30,
  "windows": 69,
  "periods": [
    {
      "id": "since1928",
      "label": "Since 1928",
      "why": "The full record, through the Depression, wars, inflation and crashes.",
      "from": 1928,
      "to": 2025,
      "nominalPct": 10.2,
      "realPct": 6.9,
      "inflationPct": 3,
      "beatShare": 62
    },
    {
      "id": "since1946",
      "label": "Since 1946",
      "why": "After World War II, when today’s global financial system began.",
      "from": 1946,
      "to": 2025,
      "nominalPct": 11.2,
      "realPct": 7.3,
      "inflationPct": 3.7,
      "beatShare": 51
    },
    {
      "id": "since1972",
      "label": "Since 1972",
      "why": "After the US left the gold standard in 1971: today’s kind of money.",
      "from": 1972,
      "to": 2025,
      "nominalPct": 11.1,
      "realPct": 7,
      "inflationPct": 3.9,
      "beatShare": 59
    },
    {
      "id": "since1982",
      "label": "Since 1982",
      "why": "The long bull market as inflation fell. An unusually good stretch.",
      "from": 1982,
      "to": 2025,
      "nominalPct": 12.1,
      "realPct": 9,
      "inflationPct": 2.9,
      "beatShare": 10
    },
    {
      "id": "since2000",
      "label": "Since 2000",
      "why": "Starting at the dot-com peak, through two crashes. Bad timing.",
      "from": 2000,
      "to": 2025,
      "nominalPct": 8.1,
      "realPct": 5.4,
      "inflationPct": 2.6,
      "beatShare": 80
    },
    {
      "id": "since2009",
      "label": "Since 2009",
      "why": "Starting just after the 2008 crash. Lucky timing.",
      "from": 2009,
      "to": 2025,
      "nominalPct": 15,
      "realPct": 12.1,
      "inflationPct": 2.6,
      "beatShare": 0
    }
  ],
  "cautious": {
    "realPct": 5,
    "beatShare": 86
  },
  "worst": {
    "from": 1965,
    "to": 1994,
    "realPct": 4.3,
    "nominalPct": 9.9,
    "inflationPct": 5.4,
    "beatShare": 100
  },
  "dividendsEstimatedAfter": "2023-06",
  "cpiGaps": [
    "2025-10"
  ]
} as const
