// Generated by scripts/build-sp500-history.mjs — do not edit by hand.
// S&P 500 total return (dividends reinvested), from Shiller's monthly data
// and BLS CPI-U, through December 2025. Dividends after 2023-06 are
// held at the last reported level, which errs cautious.

export interface Sp500Period {
  id: string
  label: string
  from: number
  to: number
  /** Average yearly return, compounded, before inflation. */
  nominalPct: number
  /** The same after inflation: what the freedom date uses. */
  realPct: number
  /** Share of all 30-year stretches since 1928 that did at least this well. */
  beatShare: number
}

export const SP500_HISTORY = {
  "through": 2025,
  "windowYears": 30,
  "windows": 69,
  "periods": [
    {
      "id": "last10",
      "label": "Last 10 years",
      "from": 2016,
      "to": 2025,
      "nominalPct": 14.7,
      "realPct": 11.1,
      "beatShare": 0
    },
    {
      "id": "last20",
      "label": "Last 20 years",
      "from": 2006,
      "to": 2025,
      "nominalPct": 10.9,
      "realPct": 8.1,
      "beatShare": 26
    },
    {
      "id": "last50",
      "label": "Last 50 years",
      "from": 1976,
      "to": 2025,
      "nominalPct": 12,
      "realPct": 8.1,
      "beatShare": 26
    },
    {
      "id": "since1928",
      "label": "Since 1928",
      "from": 1928,
      "to": 2025,
      "nominalPct": 10.2,
      "realPct": 6.9,
      "beatShare": 62
    }
  ],
  "cautious": {
    "realPct": 5,
    "beatShare": 86
  },
  "worst": {
    "from": 1965,
    "to": 1994,
    "realPct": 4.3,
    "beatShare": 100
  },
  "dividendsEstimatedAfter": "2023-06",
  "cpiGaps": [
    "2025-10"
  ]
} as const
